"""The generated output-schema surface, proved through a real generated package.

Replacement coverage for four rows whose tests retired with ``test_gen_schemas.py``
(ledger L-149) and had no recorded heir (narrow-correction step 4, rev-2 brief):

- REQ-GEN-03 — multi-output modules (2+ outputs) get a ``MultiOutput`` schema in
  ``schemas/``; single-output modules get none.
- REQ-OSR-02 — the schema is a *named* ``MultiOutput`` subclass.
- REQ-OSR-03 — its field names are exactly the graph-declared
  ``PipelineModule.outputs[i].field_name`` values.
- REQ-OSR-05 — output fields carry no defaults: every field is required.

The package is generated by the public ``run_codegen`` from the committed
``fusion_tea`` v6 snapshot, so the proof is license-free and runs the shipped
route end to end, not the generation helpers. The fixture carries both shapes on
purpose — one multi-output calculation definition (``Meier_HIF_Driver_Cost``,
used by two calc usages, which also pins one-schema-per-definition) and several
single-output definitions — and the test refuses to pass vacuously if either
shape disappears from the fixture.

The generated schema imports ``simkit.config.schema.MultiOutput``. The real
simkit is an execution-lane concern (`tests/execution/real_teax.py`); here a
minimal pydantic stand-in is installed only if simkit is absent, which preserves
pydantic field semantics (``is_required``) without freezing simkit internals.
"""

from __future__ import annotations

import importlib.util
import sys
import types
from pathlib import Path

import pytest
from pydantic import BaseModel

from sysml_codegen.cli import GenerationConfig, run_codegen
from sysml_codegen.orchestration.exact_pipeline_context import (
    build_exact_pipeline_context_from_snapshot,
)
from sysml_codegen.resolution.models import ModuleKind
from tests.conftest import FIXTURES_DIR

V6_SNAPSHOT = FIXTURES_DIR / "fusion_tea" / "instance_graph_snapshot.json"
PACKAGE = "output_schema_probe"


@pytest.fixture(scope="module")
def package(tmp_path_factory) -> Path:
    output = tmp_path_factory.mktemp("output-schema") / PACKAGE
    assert run_codegen(
        GenerationConfig(
            output_path=output,
            from_snapshot=V6_SNAPSHOT,
            package_name=PACKAGE,
            overwrite=True,
        )
    ), "the public route must generate the fusion_tea package from its committed snapshot"
    return output


@pytest.fixture(scope="module")
def calc_modules():
    """The graph's calculation modules, from the same snapshot the package used."""
    graph = build_exact_pipeline_context_from_snapshot(V6_SNAPSHOT).computation_graph
    return [
        module
        for module in graph.modules
        if module.module_kind not in (ModuleKind.CONSTRAINT, ModuleKind.REPORT_AGGREGATOR)
    ]


def _load_with_simkit_stand_in(path: Path):
    """Import a generated schema module, standing in for simkit only if absent."""
    installed: list[str] = []
    if importlib.util.find_spec("simkit") is None:
        schema_mod = types.ModuleType("simkit.config.schema")

        class MultiOutput(BaseModel):
            pass

        schema_mod.MultiOutput = MultiOutput
        config_mod = types.ModuleType("simkit.config")
        config_mod.schema = schema_mod
        simkit_mod = types.ModuleType("simkit")
        simkit_mod.config = config_mod
        for name, mod in (
            ("simkit", simkit_mod),
            ("simkit.config", config_mod),
            ("simkit.config.schema", schema_mod),
        ):
            sys.modules[name] = mod
            installed.append(name)
    try:
        spec = importlib.util.spec_from_file_location(f"generated_{path.stem}", path)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    finally:
        for name in installed:
            sys.modules.pop(name, None)


def test_the_fixture_still_carries_both_output_shapes(calc_modules) -> None:
    """Anti-vacuity: the proof below is only a proof while both shapes exist."""
    multi = {m.calc_def_name for m in calc_modules if len(m.outputs) >= 2}
    single = {m.calc_def_name for m in calc_modules if len(m.outputs) == 1}
    assert multi, "fusion_tea lost its multi-output definition; re-anchor this test"
    assert single, "fusion_tea lost its single-output definitions; re-anchor this test"


def test_multi_output_definitions_get_exactly_one_schema_and_single_output_get_none(
    package: Path, calc_modules
) -> None:
    """REQ-GEN-03: the schema choice is decided by the graph's output count."""
    expected = {
        f"{m.calc_def_name.lower()}_output.py"
        for m in calc_modules
        if len(m.outputs) >= 2
    }
    on_disk = {
        p.name for p in (package / "schemas").glob("*_output.py")
    }
    assert on_disk == expected, (
        "schemas/ must hold exactly one MultiOutput schema per multi-output "
        f"calculation definition: expected {sorted(expected)}, found {sorted(on_disk)}"
    )


def test_each_schema_is_a_named_multioutput_subclass_with_exact_required_fields(
    package: Path, calc_modules
) -> None:
    """REQ-OSR-02/03/05 through the generated bytes, imported as real pydantic."""
    by_def: dict[str, list] = {}
    for module in calc_modules:
        if len(module.outputs) >= 2:
            by_def.setdefault(module.calc_def_name, []).append(module)

    for calc_def_name, modules in sorted(by_def.items()):
        declared = {tuple(o.field_name for o in m.outputs) for m in modules}
        assert len(declared) == 1, (
            f"{calc_def_name}: its usages disagree on output order; "
            "one shared schema cannot be field-faithful to both"
        )
        field_names = declared.pop()

        schema_path = package / "schemas" / f"{calc_def_name.lower()}_output.py"
        generated = _load_with_simkit_stand_in(schema_path)

        class_name = f"{calc_def_name}Output"
        schema_cls = getattr(generated, class_name, None)
        assert schema_cls is not None, (
            f"{schema_path.name} must define the named subclass {class_name} (REQ-OSR-02)"
        )
        assert any(base.__name__ == "MultiOutput" for base in schema_cls.__mro__[1:]), (
            f"{class_name} must subclass MultiOutput (REQ-OSR-02)"
        )

        assert tuple(schema_cls.model_fields) == field_names, (
            f"{class_name} fields must be exactly the graph-declared output field "
            f"names (REQ-OSR-03): declared {field_names}, "
            f"generated {tuple(schema_cls.model_fields)}"
        )

        defaulted = [
            name
            for name, field in schema_cls.model_fields.items()
            if not field.is_required()
        ]
        assert defaulted == [], (
            f"{class_name} output fields must never carry defaults (REQ-OSR-05): "
            f"{defaulted}"
        )
