"""Generate a package from the exact route, live and from a v6 snapshot.

This is Slice 3B's product-level check: the receipt-bound context is a real
input to the shipped generation steps, and the two routes produce the same
package apart from provenance comments.

It drives the generation helpers directly rather than the ``generate`` CLI. The
CLI's ``--from-snapshot`` is the v5 route and stays the shipped authority for
this slice; giving the exact route a second public flag would be the dual
authority the recovery plan bans before Slice 3E.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pytest

from sysml_codegen.cli import (
    GenerationConfig,
    _generate_entry_points,
    _generate_modules,
    _generate_pipeline,
    _generate_registry,
    _generate_schemas,
    _generate_stencils,
    _get_template_env,
    _setup_output_directories,
)
from sysml_codegen.generation.constraint_plan import build_constraint_generation_plan
from sysml_codegen.orchestration.exact_pipeline_context import (
    build_exact_pipeline_context,
    build_exact_pipeline_context_from_snapshot,
)
from sysml_codegen.snapshot.capture import capture_instance_graph_snapshot
from tests.conftest import FIXTURES_DIR, requires_license

pytestmark = requires_license

FIXTURE = FIXTURES_DIR / "source_identity_mixed_consumers"
PACKAGE = "exact_smoke"


def _generate(context, output_path: Path) -> Path:
    config = GenerationConfig(
        output_path=output_path, package_name=PACKAGE, pipeline_name="exact_pipeline"
    )
    template_env = _get_template_env()
    plan = build_constraint_generation_plan(context, template_env, config.package_name)
    _setup_output_directories(config)
    _generate_schemas(context, config, template_env)
    _generate_modules(context, config, template_env, plan)
    _generate_stencils(context, config, template_env)
    _generate_pipeline(context, config, template_env)
    _generate_registry(context, config, template_env)
    _generate_entry_points(context, config, template_env)
    return output_path


def _tree(root: Path) -> dict[str, str]:
    return {
        str(path.relative_to(root)): path.read_text()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


@pytest.fixture(scope="module")
def packages(tmp_path_factory):
    root = tmp_path_factory.mktemp("exact-package")
    live = _generate(build_exact_pipeline_context([FIXTURE]), root / "live")

    captured = capture_instance_graph_snapshot([FIXTURE], root / "case.json")
    relocated = root / "moved" / "case.json"
    relocated.parent.mkdir()
    shutil.copyfile(captured, relocated)
    from_snapshot = _generate(
        build_exact_pipeline_context_from_snapshot(relocated), root / "v6"
    )
    return _tree(live), _tree(from_snapshot)


def test_both_routes_generate_the_same_package_files(packages) -> None:
    live, from_snapshot = packages
    assert live, "the live route generated nothing"
    assert set(live) == set(from_snapshot)


def test_the_input_json_and_schema_are_named_from_the_model_on_both_routes(packages) -> None:
    """The 3B fix, at the product surface: no ``root_0_params`` from a snapshot.

    ``source_identity_mixed_consumers/model.sysml`` declares package
    ``source_identity_mixed_consumers``, so both routes must ship that name. The
    v6 route used to ship ``inputs/root_0_params.json`` and ``Root0Params``,
    named after the ``root-0`` staging directory.
    """
    live, from_snapshot = packages
    expected_json = "inputs/source_identity_mixed_consumers_params.json"

    assert expected_json in live
    assert expected_json in from_snapshot
    assert live[expected_json] == from_snapshot[expected_json]
    assert not [name for name in from_snapshot if "root_0" in name or "root-0" in name]

    schema = next(name for name in from_snapshot if name.startswith("schemas/") and "param" in name)
    assert "class SourceIdentityMixedConsumersParams" in from_snapshot[schema]
    assert "Root0Params" not in from_snapshot[schema]


def test_the_two_packages_differ_only_in_provenance_comments(packages) -> None:
    """Name every differing file and prove the difference is the source line only.

    Module ``source_file`` is genuinely route-dependent — the live route knows
    the checkout path, a relocated snapshot knows only its referent — and it
    reaches generated bytes as a ``SysML Source:`` comment. Anything else
    differing would be a real divergence, so this asserts the whole set.
    """
    live, from_snapshot = packages
    differing = {name for name in live if live[name] != from_snapshot[name]}

    for name in differing:
        live_only = set(live[name].splitlines()) - set(from_snapshot[name].splitlines())
        snapshot_only = set(from_snapshot[name].splitlines()) - set(live[name].splitlines())
        assert live_only, f"{name} differs but has no line unique to the live route"
        assert all("SysML Source:" in line or "sysml_source" in line for line in live_only), (
            f"{name} differs somewhere other than its provenance comment: {sorted(live_only)[:3]}"
        )
        assert all(
            "SysML Source:" in line or "sysml_source" in line for line in snapshot_only
        ), f"{name} differs somewhere other than its provenance comment"

    assert differing, "expected the provenance divergence pinned by test_snapshot_v6_routes"


def test_the_generated_entry_point_json_carries_the_modelled_defaults(packages) -> None:
    """One value traced by hand from the model into the generated input file."""
    import json

    live, _ = packages
    payload = json.loads(live["inputs/source_identity_mixed_consumers_params.json"])

    # model.sysml binds the stamp plant's efficiency; read it out of the model,
    # not out of the other route's copy of this file.
    source = (FIXTURE / "model.sysml").read_text()
    assert ":>> efficiency = 0.75;" in source
    assert payload["source_identity_mixed_consumers__stamp_plant__efficiency"] == 0.75
