"""How much of a model's authored constraint domain was actually assessed (Item 3 / D3).

A report that says `all_satisfied` when two of nine gates ran is not wrong about the two —
it is wrong about the denominator. This module computes the denominator, once, at generation,
from the sealed catalog, by a total function over Item 2's closed vocabularies.

**The bucket table is the whole rule.** Every ``ConstraintCatalogUsageRecord`` lands in
exactly one of four buckets, decided by two predicates and the disposition kind:

===  ==========  ==============  ===========================  ==================
 #    asserted    inapplicable    ``disposition_kind``          bucket
===  ==========  ==============  ===========================  ==================
 1    no          either          any                          inventory only
 2    yes         yes             any                          inapplicable gate
 3    yes         no              ``eligible``                 assessed gate
 4    yes         no              ``excluded``/``non_reaching`` unassessed gate
===  ==========  ==============  ===========================  ==================

Row 1 is "plain and requirement-side usages are never applicable asserted gates". Row 2 is
"a usage stops being applicable only when it carries an explicit inapplicability
disposition". Rows 3 and 4 are the form-not-predicate test: an asserted gate the profile
excluded, or that reached nothing, stays in the denominator as an *unassessed* one. Nothing
in the table consults the predicate, and ``disposition_kind`` is closed to three values, so
the rows are exhaustive and mutually exclusive.

Row 2 combined with ``eligible`` is an authoring contradiction rather than a bucket, and
:func:`coverage_account` refuses it by name (D9) — see :func:`_refuse_inapplicable_live_gate`.
"""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Literal

from sysml_codegen.core.errors import CodeGenerationError
from sysml_codegen.elaboration.graph import ASSERTED_SOURCE_FORMS, DISPOSITION_REASONS

if TYPE_CHECKING:
    from sysml_codegen.resolution.models import (
        ConstraintCatalog,
        ConstraintCatalogUsageRecord,
    )

#: Every reason token this derivation was written against, and the ruling each one carries.
#:
#: The value is where the token sits relative to the **feasibility denominator**
#: (``applicable_gate_total``) when it appears on an *asserted, unmarked* usage — which is
#: the only situation where a reason token reaches the accounting at all. A reason on a
#: non-asserted usage is bucket 1 and a reason beside an inapplicability marker is bucket 2;
#: neither consults this map.
#:
#: The map is compared against :data:`DISPOSITION_REASONS` at generation, not only when a
#: record happens to carry a token, so a reason Item 2 adds later refuses by name instead of
#: being silently bucketed. Adding a cause for a gate not being assessed is exactly the kind
#: of change that needs a coverage ruling.
KNOWN_REASONS: Mapping[str, str] = {
    # eligible
    "admitted": "inside the denominator, and assessed — the gate ran",
    # excluded: the profile refused to execute an asserted gate the author wrote
    "out_of_scope_satisfy": "inside the denominator, unassessed",
    "out_of_profile_owner": "inside the denominator, unassessed",
    "non_numerical": "inside the denominator, unassessed",
    "unassessed_form": "inside the denominator, unassessed",
    "profile_blocked": "inside the denominator, unassessed",
    # non_reaching: nothing ever instantiated the gate's owner
    "owner_absent": "inside the denominator, unassessed",
    "owner_kind_unattachable": "inside the denominator, unassessed",
    "owner_has_no_occurrences": "inside the denominator, unassessed",
    "classification_incomplete": "inside the denominator, unassessed",
}

CoverageState = Literal["complete", "partial", "none"]


@dataclass(frozen=True)
class CoverageAccountData:
    """What a model authored, how much of it was a gate, and how much of that ran.

    The generated ``CoverageAccount`` pydantic model mirrors these fields; this is the
    producer-side value, pure and license-free, so the accounting can be proved before any
    template, version, or generated byte moves.
    """

    authored_usage_total: int
    applicable_gate_total: int
    assessed_gate_count: int
    unassessed_gate_count: int
    inapplicable_gate_count: int
    unassessed_reasons: Mapping[str, int] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """The arithmetic identities, so a bad account cannot leave this module.

        These are the same identities the generated model's validators carry. Asserting them
        at both ends is deliberate: this one catches a derivation bug here, where the fix is
        cheap; the validator catches a bake that was corrupted between here and the template.
        """
        if self.assessed_gate_count + self.unassessed_gate_count != self.applicable_gate_total:
            raise CodeGenerationError(
                "coverage account is internally inconsistent: "
                f"assessed {self.assessed_gate_count} + unassessed "
                f"{self.unassessed_gate_count} != applicable {self.applicable_gate_total}"
            )
        if sum(self.unassessed_reasons.values()) != self.unassessed_gate_count:
            raise CodeGenerationError(
                "coverage account is internally inconsistent: unassessed_reasons sums to "
                f"{sum(self.unassessed_reasons.values())}, not {self.unassessed_gate_count}"
            )
        counted = self.applicable_gate_total + self.inapplicable_gate_count
        if counted > self.authored_usage_total:
            raise CodeGenerationError(
                "coverage account is internally inconsistent: "
                f"{counted} gates accounted against {self.authored_usage_total} authored usages"
            )

    @property
    def coverage_state(self) -> CoverageState:
        """The coverage axis itself, carried so it survives a higher-precedence headline.

        A ``violation`` report still says whether the denominator was whole. That is the
        distinction a design search needs: "rejected on physics, fully covered" is a
        different candidate from "rejected on physics, sixty gates unchecked".
        """
        if self.applicable_gate_total == 0:
            return "none"
        return "complete" if self.unassessed_gate_count == 0 else "partial"

    def as_mapping(self) -> dict[str, object]:
        """The account as the generated ``CoverageAccount`` receives it."""
        return {
            "authored_usage_total": self.authored_usage_total,
            "applicable_gate_total": self.applicable_gate_total,
            "assessed_gate_count": self.assessed_gate_count,
            "unassessed_gate_count": self.unassessed_gate_count,
            "inapplicable_gate_count": self.inapplicable_gate_count,
            "unassessed_reasons": dict(self.unassessed_reasons),
            "coverage_state": self.coverage_state,
        }


def assert_reason_vocabulary_is_known(
    disposition_reasons: Mapping[str, frozenset[str]] = DISPOSITION_REASONS,
) -> None:
    """Refuse a reason token this derivation has no ruling for.

    Bucketing an unknown reason silently would be the failure, not the inconvenience: a new
    cause for a gate not being assessed is a new question about whether that gate belongs
    inside the feasibility denominator, and only a person can answer it.
    """
    authored = {reason for reasons in disposition_reasons.values() for reason in reasons}
    untaught = sorted(authored - set(KNOWN_REASONS))
    if untaught:
        raise CodeGenerationError(
            "coverage derivation has not been taught reason "
            + ", ".join(repr(reason) for reason in untaught)
            + ": rule whether it sits inside or outside the feasibility denominator, then "
            "add it to KNOWN_REASONS in generation/coverage.py"
        )


def _is_asserted(record: ConstraintCatalogUsageRecord) -> bool:
    """Does this usage ask for its predicate to be enforced?

    ``definition_typed``, ``inline``, and ``named_usage_reference`` do. A bare ``constraint``,
    a requirement-side ``require constraint``, and a ``satisfy`` reference state a condition
    without asking for it to be checked, so they are inventory and never gates.
    """
    return record.source_form in ASSERTED_SOURCE_FORMS


def _is_inapplicable(record: ConstraintCatalogUsageRecord) -> bool:
    """Did the author explicitly declare this gate out of the feasible set?

    The catalog spelling is ``inapplicability_reason``; the graph record spells the same
    decision ``inapplicability``. This function sees the catalog.
    """
    return record.inapplicability_reason is not None


def _refuse_inapplicable_live_gate(record: ConstraintCatalogUsageRecord) -> None:
    """D9: an inapplicability marker on a gate that demonstrably ran refuses generation.

    ``eligible`` is decided only for a usage that expanded to at least one scope, so
    ``eligible`` means "it produced entries" and no separate occurrence test is needed.

    The alternative — honour the marker and drop the gate — would make one doc comment a
    silent kill-switch for a live physics check: delete a failing gate from the denominator
    and the headline reads full satisfaction over a set that quietly shrank. That is the
    exact class of defect this epic exists to end.
    """
    if record.disposition_kind == "eligible" and _is_inapplicable(record):
        raise CodeGenerationError(
            f"{record.usage_qualified_name} ({record.declaration_id}) is marked inapplicable "
            f"but produced {record.occurrence_count} executable entries: an inapplicability "
            "marker states a gate is not part of the feasible set, and this gate ran. Remove "
            "the marker, or stop asserting the gate."
        )


def coverage_account(catalog: ConstraintCatalog) -> CoverageAccountData:
    """The coverage account this catalog implies, by D3's bucket table.

    Total over Item 2's closed vocabularies: every usage record lands in exactly one bucket,
    and ``authored_usage_total`` falls out as the sum.
    """
    assert_reason_vocabulary_is_known()

    applicable_gate_total = 0
    assessed_gate_count = 0
    unassessed_gate_count = 0
    inapplicable_gate_count = 0
    unassessed_reasons: dict[str, int] = {}

    for record in catalog.usage_records:
        _refuse_inapplicable_live_gate(record)

        if not _is_asserted(record):
            continue  # row 1 — inventory only
        if _is_inapplicable(record):
            inapplicable_gate_count += 1  # row 2 — removed from the denominator
            continue

        applicable_gate_total += 1
        if record.disposition_kind == "eligible":
            assessed_gate_count += 1  # row 3
        else:
            unassessed_gate_count += 1  # row 4 — excluded or non_reaching
            reason = record.disposition_reason
            unassessed_reasons[reason] = unassessed_reasons.get(reason, 0) + 1

    return CoverageAccountData(
        authored_usage_total=len(catalog.usage_records),
        applicable_gate_total=applicable_gate_total,
        assessed_gate_count=assessed_gate_count,
        unassessed_gate_count=unassessed_gate_count,
        inapplicable_gate_count=inapplicable_gate_count,
        unassessed_reasons=dict(sorted(unassessed_reasons.items())),
    )


__all__ = [
    "KNOWN_REASONS",
    "CoverageAccountData",
    "CoverageState",
    "assert_reason_vocabulary_is_known",
    "coverage_account",
]
