"""Entry point schema and JSON generation for pipeline inputs.

Generates from ComputationGraph entry_point_groups:
- Parameter group Pydantic schemas
- JSON files with default values for all parameters
"""

import json
import logging
from pathlib import Path
from typing import Any

import jinja2

from sysml_codegen.generation.type_mapping import map_sysml_type_to_python

logger = logging.getLogger(__name__)


def generate_inputs_readme(
    parameter_groups: list,  # List[DerivedParameterGroup]
    package_name: str = "generated_code",
) -> str:
    """Generate README.md for the inputs directory.

    Dynamically generates documentation based on actual parameter groups
    derived from SysML models. No hardcoded values.

    Args:
        parameter_groups: List of DerivedParameterGroup from ParameterGroupDeriver
        package_name: Package name (parameterized)

    Returns:
        README.md content as string
    """
    # Count total parameters
    total_params = sum(len(g.parameters) for g in parameter_groups)

    # Build README content
    readme = [
        "# Input Parameters",
        "",
        "This directory contains input parameter files for the simulation pipeline.",
        "Parameters are extracted from SysML design files via Phase B code generation.",
        "",
        "## Files",
        "",
        f"Parameters are organized into **{len(parameter_groups)} JSON files**:",
        "",
        "| File | Schema Class | Parameters |",
        "|------|--------------|------------|",
    ]

    # Add file table dynamically
    for group in parameter_groups:
        readme.append(
            f"| `{group.name}.json` | `{group.class_name}` | {len(group.parameters)} |"
        )

    readme.extend(
        [
            "",
            "## Overview",
            "",
            f"The input files contain **{total_params} parameters** extracted from",
            "the SysML models. These parameters represent the entry points to the simulation",
            "pipeline - values that must be provided externally and are not computed by any",
            "internal calculation module.",
            "",
            "## Usage",
            "",
            "### Loading Parameters",
            "",
        ]
    )

    # Add dynamic usage example using first group (if available)
    if parameter_groups:
        first = parameter_groups[0]
        readme.extend(
            [
                "To load parameters from a group:",
                "",
                "```python",
                "import json",
                f"from {package_name}.schemas.{first.name} import {first.class_name}",
                "",
                "# Load JSON file",
                f'with open("{package_name}/inputs/{first.name}.json") as f:',
                "    data = json.load(f)",
                "",
                "# Validate against schema",
                f"params = {first.class_name}(**data)",
                "```",
                "",
            ]
        )

    readme.extend(
        [
            "### Creating Custom Scenarios",
            "",
            "To create a custom scenario:",
            "",
            "1. Copy the JSON files to new files (e.g., `high_power_plasma_params.json`)",
            "2. Edit the parameter values in the new files",
            "3. Update the pipeline YAML to reference your new files",
            "",
            "## Schema Reference",
            "",
            "For complete parameter definitions, constraints, and types, see:",
            "",
            f"- `{package_name}/schemas/*_params.py` - Pydantic schemas with full type information",
            "",
            "## Notes",
            "",
            "- Parameters are grouped by their source (design file or library package)",
            "- Parameters with `null` values require explicit values before pipeline execution",
            "- The schemas enforce type validation and constraints at runtime",
            "- Files are generated by code generation scripts",
            "",
        ]
    )

    return "\n".join(readme)


def generate_derived_group_schema(
    group,  # DerivedParameterGroup
    template_env: jinja2.Environment,
    output_path: Path,
) -> str:
    """Generate Pydantic schema for a derived parameter group.

    Args:
        group: DerivedParameterGroup with parameters and defaults
        template_env: Jinja2 environment with templates loaded
        output_path: Output file path (for reference/logging)

    Returns:
        Generated Python code string for the schema
    """
    # Build field list from ParameterSource objects
    fields: list[dict[str, Any]] = []

    for param in group.parameters:
        # Map SysML type to Python type
        python_type = map_sysml_type_to_python(param.sysml_type)

        # Build field dict with default from derivation
        field: dict[str, Any] = {
            "name": param.name,
            "type": python_type,
            "description": param.description or f"Parameter {param.name}",
            "default": param.default_value,
        }
        fields.append(field)

    # Build description based on source type
    if group.source_type == "design":
        description = f"Parameters from {group.source_identifier}.\n\nSource Type: Design file"
    else:
        description = f"Parameters from library {group.source_identifier}.\n\nSource Type: Library (no defaults)"

    # Build template context
    context = {
        "class_name": group.class_name,
        "description": description,
        "fields": fields,
    }

    # Render template
    template = template_env.get_template("parameter_group_schema.py.jinja2")
    schema_code = template.render(**context)

    # Ensure final newline (PEP 8)
    if not schema_code.endswith("\n"):
        schema_code += "\n"

    logger.info(
        f"Generated derived schema '{group.class_name}' with {len(fields)} parameters: {output_path}"
    )

    return schema_code


def generate_derived_group_json(
    group,  # DerivedParameterGroup
    output_path: Path,
) -> str:
    """Generate JSON input file for a derived parameter group.

    Args:
        group: DerivedParameterGroup with parameters and defaults
        output_path: Output file path (for reference/logging)

    Returns:
        JSON string with all parameters and their defaults
    """
    # Build dictionary from parameters
    data = {}
    for param in group.parameters:
        data[param.name] = param.default_value

    # Render JSON with sorted keys for deterministic output
    json_content = json.dumps(data, indent=2, sort_keys=True)

    # Ensure final newline
    if not json_content.endswith("\n"):
        json_content += "\n"

    logger.info(
        f"Generated derived JSON '{group.name}' with {len(data)} parameters: {output_path}"
    )

    return json_content


def generate_all_derived_schemas(
    entry_point_groups: list,  # list[models.ParameterGroup]
    template_env: jinja2.Environment,
    output_dir: Path,
) -> list[Path]:
    """Generate Pydantic schema files from ComputationGraph entry_point_groups.

    Args:
        entry_point_groups: ParameterGroup list from ComputationGraph
        template_env: Jinja2 environment with templates loaded
        output_dir: Output directory (schemas/ subdirectory will be used)

    Returns:
        List of generated schema file paths
    """
    schemas_dir = output_dir / "schemas"
    schemas_dir.mkdir(parents=True, exist_ok=True)

    generated_files = []
    for group in entry_point_groups:
        # Build field list from EntryPoint objects
        fields: list[dict[str, Any]] = []
        for ep in group.parameters:
            field: dict[str, Any] = {
                "name": ep.qualified_name,
                "type": getattr(ep, "python_type", "float"),
                "description": f"Entry point: {ep.simple_name}",
                "default": ep.default_value,
            }
            fields.append(field)

        # Build description from source file
        description = f"Parameters from {group.source_file}."

        # Build template context
        context = {
            "class_name": group.class_name,
            "description": description,
            "fields": fields,
        }

        # Render template
        template = template_env.get_template("parameter_group_schema.py.jinja2")
        content = template.render(**context)

        # Ensure final newline (PEP 8)
        if not content.endswith("\n"):
            content += "\n"

        output_path = schemas_dir / f"{group.name}.py"
        output_path.write_text(content)
        generated_files.append(output_path)

    logger.info(f"Generated {len(generated_files)} parameter group schemas from graph")
    return generated_files


def generate_all_derived_jsons(
    entry_point_groups: list,  # list[models.ParameterGroup]
    output_dir: Path,
) -> list[Path]:
    """Generate JSON input files from ComputationGraph entry_point_groups.

    Args:
        entry_point_groups: ParameterGroup list from ComputationGraph
        output_dir: Output directory (inputs/ subdirectory will be used)

    Returns:
        List of generated JSON file paths
    """
    inputs_dir = output_dir / "inputs"
    inputs_dir.mkdir(parents=True, exist_ok=True)

    generated_files = []
    for group in entry_point_groups:
        # Build dictionary from EntryPoint objects
        data = {}
        for ep in group.parameters:
            if ep.default_value is not None:
                data[ep.qualified_name] = ep.default_value

        # Render JSON with sorted keys for deterministic output
        json_content = json.dumps(data, indent=2, sort_keys=True)

        # Ensure final newline
        if not json_content.endswith("\n"):
            json_content += "\n"

        output_path = inputs_dir / f"{group.name}.json"
        output_path.write_text(json_content)
        generated_files.append(output_path)

    logger.info(f"Generated {len(generated_files)} JSON templates from graph")
    return generated_files


# Keep old names as aliases for backward compatibility during transition
generate_all_derived_schemas_from_graph = generate_all_derived_schemas
generate_all_derived_jsons_from_graph = generate_all_derived_jsons


__all__ = [
    "generate_all_derived_jsons",
    "generate_all_derived_jsons_from_graph",
    "generate_all_derived_schemas",
    "generate_all_derived_schemas_from_graph",
    "generate_derived_group_json",
    "generate_derived_group_schema",
    "generate_inputs_readme",
]
